# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 14:37
from __future__ import unicode_literals

from django.db import migrations
import isi_mip.contrib.blocks
import isi_mip.pages.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_create_initial_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcomespage',
            name='papers',
        ),
        migrations.AddField(
            model_name='outcomespage',
            name='content',
            field=wagtail.fields.StreamField((('papers', wagtail.blocks.StructBlock((('title', wagtail.blocks.CharBlock()), ('papers', wagtail.blocks.ListBlock(isi_mip.pages.blocks.PaperBlock))))),), default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gettingstartedpage',
            name='content',
            field=wagtail.fields.StreamField((('input_data', wagtail.blocks.StructBlock((('description', wagtail.blocks.RichTextBlock()), ('row_limit', isi_mip.contrib.blocks.IntegerBlock(default=10, max_value=30, min_value=1))))), ('contact', wagtail.blocks.StructBlock((('description', wagtail.blocks.RichTextBlock()), ('sectors', wagtail.blocks.ListBlock(isi_mip.pages.blocks.SectorBlock))))), ('blog', wagtail.blocks.StructBlock((('blog_index', isi_mip.contrib.blocks.SpecificPageChooserBlock(help_text='Select blog index page.', required=False)), ('title', wagtail.blocks.CharBlock(help_text='Per default, the title of the blog index will be used.', required=False)), ('entry_count', isi_mip.contrib.blocks.IntegerBlock(default=4, help_text='How many blog entries should be displayed?', max_value=5, min_value=1, required=True))), template='blocks/flat_blog_block.html')))),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField((('row', wagtail.blocks.StreamBlock((('teaser', wagtail.blocks.StructBlock((('title', wagtail.blocks.CharBlock(required=True)), ('picture', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.blocks.TextBlock(required=True)), ('link', wagtail.blocks.PageChooserBlock(required=True))))), ('bigteaser', wagtail.blocks.StructBlock((('title', wagtail.blocks.CharBlock(required=True)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('picture', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.blocks.RichTextBlock()), ('external_link', wagtail.blocks.URLBlock(help_text='Will be ignored if an internal link is provided', required=False)), ('internal_link', wagtail.blocks.PageChooserBlock(help_text='If set, this has precedence over the external link.', required=False)), ('from_date', wagtail.blocks.DateBlock(required=False)), ('to_date', wagtail.blocks.DateBlock(required=False))))), ('blog', wagtail.blocks.StructBlock((('blog_index', isi_mip.contrib.blocks.SpecificPageChooserBlock(help_text='Select blog index page.', required=False)), ('title', wagtail.blocks.CharBlock(help_text='Per default, the title of the blog index will be used.', required=False)), ('entry_count', isi_mip.contrib.blocks.IntegerBlock(default=4, help_text='How many blog entries should be displayed?', max_value=5, min_value=1, required=True))))), ('numbers', wagtail.blocks.StructBlock((('number1', wagtail.blocks.CharBlock()), ('number2', wagtail.blocks.CharBlock())))), ('twitter', wagtail.blocks.StructBlock((('username', wagtail.blocks.CharBlock(required=True)),)))))),)),
        ),
        migrations.AlterField(
            model_name='impactmodelspage',
            name='content',
            field=wagtail.fields.StreamField((('impact_models', wagtail.blocks.StructBlock((('description', wagtail.blocks.RichTextBlock()), ('rows_per_page', isi_mip.contrib.blocks.IntegerBlock(default=20, min_value=1, required=True))))), ('blog', wagtail.blocks.StructBlock((('blog_index', isi_mip.contrib.blocks.SpecificPageChooserBlock(help_text='Select blog index page.', required=False)), ('title', wagtail.blocks.CharBlock(help_text='Per default, the title of the blog index will be used.', required=False)), ('entry_count', isi_mip.contrib.blocks.IntegerBlock(default=4, help_text='How many blog entries should be displayed?', max_value=5, min_value=1, required=True))), template='blocks/flat_blog_block.html')))),
        ),
        migrations.AlterField(
            model_name='outputdatapage',
            name='content',
            field=wagtail.fields.StreamField((('output_data', wagtail.blocks.StructBlock((('description', wagtail.blocks.RichTextBlock()),))), ('blog', wagtail.blocks.StructBlock((('blog_index', isi_mip.contrib.blocks.SpecificPageChooserBlock(help_text='Select blog index page.', required=False)), ('title', wagtail.blocks.CharBlock(help_text='Per default, the title of the blog index will be used.', required=False)), ('entry_count', isi_mip.contrib.blocks.IntegerBlock(default=4, help_text='How many blog entries should be displayed?', max_value=5, min_value=1, required=True))), template='blocks/flat_blog_block.html')))),
        ),
    ]
