# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-09 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_auto_20200514_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='number3_imported_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='number3_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='number4_imported_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='number4_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
