# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-05-21 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_auto_20201009_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperpage',
            name='is_peer_reviewed',
            field=models.BooleanField(default=True),
        ),
    ]
