# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-05-25 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_paperpage_is_peer_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperpage',
            name='is_peer_reviewed',
        ),
        migrations.AddField(
            model_name='paperpage',
            name='is_not_peer_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
