# Generated by Django 3.2.11 on 2022-01-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_auto_20220118_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='gettingstartedpage',
            name='is_input_data_parent_page',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
