# Generated by Django 3.2.11 on 2022-10-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0007_auto_20220118_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='involved',
            new_name='responsible',
        ),
    ]
