# Generated by Django 3.2.11 on 2022-10-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0124_rename_responsible_person_impactmodel_additional_persons_involved'),
        ('contrib', '0009_alter_userprofile_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='impact_model_owner', to='climatemodels.BaseImpactModel', verbose_name='Owner (LEGACY)'),
        ),
    ]
