# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-31 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0103_auto_20190603_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='protocol_relation',
            field=models.CharField(choices=[('P', 'Protocol'), ('S', 'Secondary')], default='P', max_length=1),
        ),
    ]
