# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-14 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0104_auto_20200331_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactmodel',
            name='model_license',
            field=models.CharField(blank=True, help_text='The license the model is linked to.', max_length=200, null=True, verbose_name='Model license'),
        ),
        migrations.AddField(
            model_name='impactmodel',
            name='model_url',
            field=models.URLField(blank=True, help_text='The homepage of the model or a link to a git tree or hash of the model version used.', null=True, verbose_name='Model Homepage'),
        ),
    ]
