# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-05-18 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0108_fire_natural_ignition_implemented'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterregional',
            name='vegetation_approach_used',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Approach used to simulate vegetation dynamics'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='vegetation_representation',
            field=models.CharField(blank=True, choices=[('prescriped', 'Prescriped'), ('simulated', 'Simulated')], max_length=255, null=True, verbose_name='How is vegetation represented?'),
        ),
    ]
