# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-05-21 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0109_auto_20210518_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterregional',
            name='calibration_methods',
            field=models.TextField(blank=True, default='', help_text='e.g.: Calibration for discharge at the basin outlet, Enhanced calibration for discharge at multiple gauges, etc.', null=True, verbose_name='Calibration and validation method'),
        ),
        migrations.AddField(
            model_name='waterregional',
            name='calibration_model_evaluated',
            field=models.NullBooleanField(default=None, verbose_name='Was the model validated/evaluated?'),
        ),
        migrations.AddField(
            model_name='waterregional',
            name='calibration_periods',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Calibration and validation periods'),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='methods_evapotranspiration',
            field=models.TextField(blank=True, default='', help_text='Is it implemented? How is it resolved?', null=True, verbose_name='Potential evapotranspiration'),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='methods_snowmelt',
            field=models.TextField(blank=True, default='', help_text='Is it implemented? How is it resolved?', null=True, verbose_name='Snow melt'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='methods_evapotranspiration',
            field=models.TextField(blank=True, default='', help_text='Is it implemented? How is it resolved?', null=True, verbose_name='Potential evapotranspiration'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='methods_snowmelt',
            field=models.TextField(blank=True, default='', help_text='Is it implemented? How is it resolved?', null=True, verbose_name='Snow melt'),
        ),
    ]
