# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-05-21 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import isi_mip.choiceorotherfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0110_auto_20210521_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodiversity',
            name='distribution_response_variable',
            field=models.CharField(blank=True, choices=[('Binomial', 'Binomial'), ('Bernoulli', 'Bernoulli'), ('Poisson', 'Poisson')], max_length=255, null=True, verbose_name='Distribution of response variable'),
        ),
        migrations.AlterField(
            model_name='biodiversity',
            name='model_output',
            field=isi_mip.choiceorotherfield.models.ChoiceOrOtherField(blank=True, choices=[('probability of occurrence', 'probability of occurrence'), ('relative probability of occurrence', 'relative probability of occurrence'), ('summed probability of occurrence', 'summed probability of occurrence'), ('species richness of taxon', 'species richness of taxon')], max_length=500, null=True, verbose_name='Model output'),
        ),
        migrations.AlterField(
            model_name='impactmodel',
            name='model_license',
            field=models.CharField(blank=True, help_text='Please note, if you want to update the model license please <a href="mailto:info@isimip.org">write to us</a>.', max_length=200, null=True, verbose_name='Model license'),
        ),
    ]
