# Generated by Django 3.2.11 on 2022-01-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0113_auto_20210525_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculture',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='agroeconomicmodelling',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='biodiversity',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='biodiversity',
            name='model_output',
            field=models.ManyToManyField(blank=True, to='climatemodels.BiodiversityModelOutput', verbose_name='Model output'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='coastalinfrastructure',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='computablegeneralequilibriummodelling',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='energy',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='fire',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='forests',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='genericsector',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='marineecosystemsglobal',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='marineecosystemsregional',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='otherinformation',
            name='spin_up',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text="'No' indicates the simulations were run starting in the first reporting year 1971", null=True, verbose_name='Was a spin-up performed?'),
        ),
        migrations.AlterField(
            model_name='permafrost',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='calibration',
            field=models.BooleanField(default=None, null=True, verbose_name='Was the model calibrated?'),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='vegetation',
            field=models.BooleanField(default=None, null=True, verbose_name='Is CO2 fertilisation accounted for?'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='calibration',
            field=models.BooleanField(default=None, null=True, verbose_name='Was the model calibrated?'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='calibration_model_evaluated',
            field=models.BooleanField(default=None, null=True, verbose_name='Was the model validated/evaluated?'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='vegetation',
            field=models.BooleanField(default=None, null=True, verbose_name='Is CO2 fertilisation accounted for?'),
        ),
    ]
