# Generated by Django 3.2.11 on 2022-01-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0114_auto_20220118_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdata',
            name='data_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='doi_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
