# Generated by Django 3.2.11 on 2022-01-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0117_rename_dataset_history_impactmodel_data_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactmodel',
            name='data_download',
            field=models.URLField(blank=True, help_text='Follow this link to access the datasets in the ISIMIP Repository.', null=True, verbose_name='Data download'),
        ),
    ]
