# Generated by Django 3.2.11 on 2022-01-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0118_alter_impactmodel_data_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactmodel',
            name='doi',
            field=models.URLField(blank=True, help_text='For more information and how to cite this dataset, please follow the DOI.', null=True, verbose_name='DOI'),
        ),
    ]
