# Generated by Django 3.2.11 on 2022-01-31 10:27

from django.db import migrations, models
import isi_mip.choiceorotherfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0119_impactmodel_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherinformation',
            name='soil_layers',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='impactmodel',
            name='version',
            field=models.CharField(blank=True, help_text='Indicate this by a version number or year of application. If the model code would change or a new model application is performed, the new model version should be documented, and this change should be reflected in the simulation files. More information on model versioning at <a href="/protocol/preparing-simulation-files/" target="_blank">https://www.isimip.org/protocol/preparing-simulation-files</a>', max_length=500, null=True, verbose_name='Model version'),
        ),
        migrations.AlterField(
            model_name='otherinformation',
            name='extreme_events',
            field=models.TextField(blank=True, default='', help_text='Key challenges for this model in reproducing impacts of extreme events such as pests, fire, water logging, frost damage.', null=True, verbose_name='Key challenges'),
        ),
        migrations.AlterField(
            model_name='otherinformation',
            name='management',
            field=models.TextField(blank=True, default='', help_text='Please specify management in the general setup. Any sector specific management information is detailed in section 6. Sector-specific information.', null=True),
        ),
        migrations.AlterField(
            model_name='technicalinformation',
            name='temporal_resolution_climate',
            field=isi_mip.choiceorotherfield.models.ChoiceOrOtherField(blank=True, choices=[('daily', 'daily'), ('monthly', 'monthly'), ('annual', 'annual'), ("5'x5'", "5'x5'"), ("0.5'x0.5'", "0.5'x0.5'")], help_text='ISIMIP data was provided in daily time steps', max_length=500, null=True, verbose_name='Temporal resolution of input data: climate variables'),
        ),
    ]
