# Generated by Django 3.2.11 on 2022-09-08 07:06

from django.db import migrations, models
import isi_mip.choiceorotherfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0121_auto_20220214_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapublicationconfirmation',
            name='confirmed_publication_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datapublicationconfirmation',
            name='confirmed_publication_date_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='impactmodel',
            name='model_license',
            field=models.CharField(blank=True, help_text='Please note, if you want to update the model license please <a href="mailto:info@isimip.org">write to us</a>.', max_length=200, null=True, verbose_name='Model output license'),
        ),
        migrations.AlterField(
            model_name='impactmodel',
            name='version',
            field=models.CharField(blank=True, help_text='Indicate this by a version number or year of application. If the model code would change or a new model application is performed, the new model version should be documented, and this change should be reflected in the simulation files. More information on model versioning you can find <a href="/protocol/preparing-simulation-files/" target="_blank">here</a>.', max_length=500, null=True, verbose_name='Model version'),
        ),
        migrations.AlterField(
            model_name='otherinformation',
            name='spin_up',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="'No' indicates the simulations were run starting in the first reporting year 1971", null=True, verbose_name='Was a spin-up performed?'),
        ),
        migrations.AlterField(
            model_name='technicalinformation',
            name='spatial_resolution',
            field=isi_mip.choiceorotherfield.models.ChoiceOrOtherField(blank=True, choices=[('0.5’ x 0.5’', '0.5’ x 0.5’'), ('1.5’ x 1.5’', '1.5’ x 1.5’'), ('6.0’ x 6.0’', '5.0’ x 5.0’'), ('0.5°x0.5°', '0.5°x0.5°')], help_text='The spatial resolution at which the ISIMIP simulations were run, if on a regular grid. Data was provided on a 0.5°x0.5° grid', max_length=500, null=True, verbose_name='Spatial Resolution'),
        ),
        migrations.AlterField(
            model_name='technicalinformation',
            name='temporal_resolution_climate',
            field=isi_mip.choiceorotherfield.models.ChoiceOrOtherField(blank=True, choices=[('annual', 'annual'), ('monthly', 'monthly'), ('daily', 'daily'), ('constant', 'constant')], help_text='ISIMIP data was provided in daily time steps. If more than one resolution is used, please include them in the custom field', max_length=500, null=True, verbose_name='Temporal resolution of input data: climate variables'),
        ),
    ]
