# Generated by Django 3.2.11 on 2022-10-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0122_auto_20220908_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapublicationconfirmation',
            name='confirmed_publication_date',
            field=models.CharField(blank=True, choices=[('as_soon_as_possible', 'as soon as possible'), ('not_before_date', 'not before date'), ('one_year_after_dkrz', 'one year after submission to DKRZ at least'), ('notify_isimip', 'the modeling group will notify the ISIMIP data team by email of the end of the emarbo period. (not later than one year after data submission)')], max_length=500, null=True, verbose_name='Confirmed publication by'),
        ),
        migrations.AlterField(
            model_name='datapublicationconfirmation',
            name='confirmed_publication_date_date',
            field=models.DateField(blank=True, null=True, verbose_name='Confirmed publication date'),
        ),
        migrations.AlterField(
            model_name='impactmodel',
            name='model_license',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Model license'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='vegetation_representation',
            field=models.CharField(blank=True, choices=[('prescriped', 'Prescribed'), ('simulated', 'Simulated')], max_length=255, null=True, verbose_name='How is vegetation represented?'),
        ),
    ]
