# Generated by Django 3.2.11 on 2022-10-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0123_auto_20221028_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impactmodel',
            old_name='responsible_person',
            new_name='additional_persons_involved',
        ),
    ]
