# Generated by Django 3.2.11 on 2022-10-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0124_rename_responsible_person_impactmodel_additional_persons_involved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactmodel',
            name='additional_persons_involved',
            field=models.CharField(blank=True, help_text='List of all additional persons involved in this model.', max_length=500, null=True, verbose_name='Additional persons involved'),
        ),
    ]
