# Generated by Django 3.2.11 on 2023-01-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0125_alter_impactmodel_additional_persons_involved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapublicationconfirmation',
            name='confirmed_publication_date',
            field=models.CharField(blank=True, choices=[('as_soon_as_possible', 'as soon as possible'), ('not_before_date', 'not before date'), ('one_year_after_dkrz', 'one year after submission to DKRZ at latest'), ('notify_isimip', 'the modeling group will notify the ISIMIP data team by email of the end of the emarbo period. (not later than one year after data submission)')], max_length=500, null=True, verbose_name='Confirmed publication by'),
        ),
    ]
