# Generated by Django 3.2.11 on 2023-01-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0127_alter_outputdata_experiments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputdata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
