# Generated by Django 3.2.18 on 2023-02-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0130_impactmodelinformation_impactmodelquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactmodelquestion',
            name='information_type',
            field=models.CharField(blank=True, choices=[('technical_information', 'Resolution'), ('input_data_information', 'Input Data'), ('other_information', 'Model Setup')], max_length=255, null=True, unique=True),
        ),
    ]
