# Generated by Django 3.2.18 on 2023-02-24 08:34

from django.db import migrations, models
import isi_mip.climatemodels.impact_model_blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0131_alter_impactmodelquestion_information_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactmodelquestion',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impactmodelquestion',
            name='heading',
            field=models.CharField(default='default', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='impactmodelquestion',
            name='questions',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='A unique name identifier for the question', required=True)), ('question', wagtail.blocks.TextBlock(help_text='The question you would like to ask', required=True)), ('required', wagtail.blocks.BooleanBlock(help_text='Is the question you are asking mandatory', required=False)), ('help_text', wagtail.blocks.TextBlock(required=False))])), ('choice_or_other', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='A unique name identifier for the question', required=True)), ('question', wagtail.blocks.TextBlock(help_text='The question you would like to ask', required=True)), ('required', wagtail.blocks.BooleanBlock(help_text='Is the question you are asking mandatory', required=False)), ('help_text', wagtail.blocks.TextBlock(required=False)), ('choices', wagtail.blocks.ListBlock(isi_mip.climatemodels.impact_model_blocks.ChoiceBlock))])), ('input_data_choice', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='A unique name identifier for the question', required=True)), ('question', wagtail.blocks.TextBlock(help_text='The question you would like to ask', required=True)), ('required', wagtail.blocks.BooleanBlock(help_text='Is the question you are asking mandatory', required=False)), ('help_text', wagtail.blocks.TextBlock(required=False)), ('input_data', wagtail.blocks.MultipleChoiceBlock(choices=isi_mip.climatemodels.impact_model_blocks.get_input_data))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
