# Generated by Django 3.2.18 on 2023-02-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0133_impactmodelquestion_subheading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactmodelquestion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='impactmodelquestion',
            name='subheading',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
