# Generated by Django 3.2.18 on 2023-02-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0134_auto_20230224_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impactmodelquestion',
            options={'ordering': ['step']},
        ),
        migrations.AddField(
            model_name='impactmodelquestion',
            name='step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
