# Generated by Django 3.2.18 on 2023-02-28 15:58

from django.db import migrations



def create_impact_model_information(apps, schema_editor):
    ImpactModel = apps.get_model('climatemodels', 'ImpactModel')
    ImpactModelInformation = apps.get_model('climatemodels', 'ImpactModelInformation')
    for impact_model in ImpactModel.objects.all():
        if not hasattr(impact_model, 'impact_model_information'):
            ImpactModelInformation.objects.create(
                impact_model=impact_model
            )

class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0135_auto_20230224_0943'),
    ]

    operations = [
        migrations.RunPython(create_impact_model_information),
    ]
