# Generated by Django 3.2.18 on 2023-03-02 10:02

from django.db import migrations, models
import django.db.models.deletion
import isi_mip.climatemodels.impact_model_blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0136_auto_create_impact_model_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactmodelinformation',
            name='impact_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='impact_model_information', serialize=False, to='climatemodels.impactmodel'),
        ),
        migrations.AlterField(
            model_name='impactmodelquestion',
            name='questions',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='A unique name identifier for the question', required=True)), ('question', wagtail.blocks.TextBlock(help_text='The question you would like to ask', required=True)), ('required', wagtail.blocks.BooleanBlock(help_text='Is the question you are asking mandatory', required=False)), ('help_text', wagtail.blocks.TextBlock(required=False)), ('textarea', wagtail.blocks.BooleanBlock(required=False))])), ('choice', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='A unique name identifier for the question', required=True)), ('question', wagtail.blocks.TextBlock(help_text='The question you would like to ask', required=True)), ('required', wagtail.blocks.BooleanBlock(help_text='Is the question you are asking mandatory', required=False)), ('help_text', wagtail.blocks.TextBlock(required=False)), ('allow_custom', wagtail.blocks.BooleanBlock(required=False)), ('choices', wagtail.blocks.ListBlock(isi_mip.climatemodels.impact_model_blocks.ChoiceBlock))])), ('multiple_choice', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='A unique name identifier for the question', required=True)), ('question', wagtail.blocks.TextBlock(help_text='The question you would like to ask', required=True)), ('required', wagtail.blocks.BooleanBlock(help_text='Is the question you are asking mandatory', required=False)), ('help_text', wagtail.blocks.TextBlock(required=False)), ('choices', wagtail.blocks.ListBlock(isi_mip.climatemodels.impact_model_blocks.ChoiceBlock))])), ('input_data_choice', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='A unique name identifier for the question', required=True)), ('question', wagtail.blocks.TextBlock(help_text='The question you would like to ask', required=True)), ('required', wagtail.blocks.BooleanBlock(help_text='Is the question you are asking mandatory', required=False)), ('help_text', wagtail.blocks.TextBlock(required=False)), ('choices', wagtail.blocks.MultipleChoiceBlock(choices=isi_mip.climatemodels.impact_model_blocks.get_input_data))])), ('true_false', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='A unique name identifier for the question', required=True)), ('question', wagtail.blocks.TextBlock(help_text='The question you would like to ask', required=True)), ('required', wagtail.blocks.BooleanBlock(help_text='Is the question you are asking mandatory', required=False)), ('help_text', wagtail.blocks.TextBlock(required=False)), ('nullable', wagtail.blocks.BooleanBlock(required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
