# Generated by Django 3.2.11 on 2022-10-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190408_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapublicationconfirmation',
            name='body',
            field=models.TextField(help_text='You can use the following tokens in the email template: {{model_contact_person}}, {{simulation_round}}, {{impact_model_name}}, {{custom_text}}, {{license}}, {{publication_by}}, {{publication_date}}'),
        ),
    ]
