# Generated by Django 3.2.18 on 2023-02-22 15:39

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_datapublicationconfirmation_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerlink',
            name='menu_items',
            field=wagtail.fields.StreamField([('jump_link', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.CharBlock())])), ('page_link', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('page', wagtail.blocks.PageChooserBlock())]))], blank=True, null=True, use_json_field=True),
        ),
    ]
